
- name: Set the hostname of the BIG-IP
  hosts: bigips
  connection: local
  
  bigip_hostname:
    hostname: bigip.ansible.test
    password: secret
    server: lb.mydomain.com
    user: admin
  delegate_to: localhost
