- name: Set the hostname of the BIG-IP
  hosts: bigips
  connection: local
  
  tasks:  
    bigip_hostname:
        hostname: bigip.ansible.test
        password: "{{ bigip_password }}"
        server: "{{ inventory_hostname }}"
        user: "{{ bigip_username }}"
    delegate_to: localhost
