- name: Set the hostname of the BIG-IP
  hosts: bigips
  connection: local
  
  tasks:  
 - name: Set the hostname of the BIG-IP
        hostname: bigip.ansible.test
        password: "{{ bigip_password }}"
        server: "{{ inventory_hostname }}"
        user: "{{ bigip_username }}"
    delegate_to: localhost
